# Generated by Django 3.1.1 on 2021-04-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=1024)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.CharField(blank=True, max_length=25, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('other_address', models.TextField(blank=True, null=True)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('total_orders_placed', models.PositiveIntegerField(blank=True, null=True)),
                ('total_orders_canceled', models.PositiveIntegerField(blank=True, null=True)),
                ('total_orders_sucessful', models.PositiveIntegerField(blank=True, null=True)),
                ('total_times_dispute_raised', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number_verfied', models.BooleanField(default=False)),
                ('mail_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
