# Generated by Django 3.1.1 on 2021-04-19 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20210419_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='order_price',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]$')]),
        ),
    ]
