# Generated by Django 3.1.1 on 2021-04-24 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0007_auto_20210419_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='customer',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
