# Generated by Django 3.1.1 on 2021-04-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_auto_20210427_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='order',
            field=models.JSONField(),
        ),
    ]
