# Generated by Django 3.1.1 on 2021-04-27 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_auto_20210427_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorders',
            old_name='order',
            new_name='location',
        ),
        migrations.AddField(
            model_name='customerorders',
            name='delivery_person_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='delivery_person_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]')]),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='mail',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='mode_of_payment',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='orders',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]')]),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='discount',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]')], verbose_name='coupon'),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='is_canceled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='is_delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
