# Generated by Django 3.1.1 on 2021-04-27 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0015_auto_20210427_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='delivery_charges',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]')]),
        ),
    ]
