# Generated by Django 3.1.1 on 2021-04-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0016_customerorders_delivery_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='ordered_date_time',
            field=models.DateTimeField(),
        ),
    ]
