# Generated by Django 3.1.1 on 2021-04-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0017_auto_20210427_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='ordered_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
