# Generated by Django 3.1.1 on 2021-04-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=70, null=True)),
                ('item_type', models.CharField(choices=[('Tiffin', 'Tiffin'), ('Chuteys', 'Chutneys'), ('Meals', 'Meals'), ('Biriyanis', 'Biriyanis'), ('Curries', 'Curries')], default=None, max_length=30)),
                ('made_of_category', models.CharField(choices=[('Normal', 'Normal'), ('Ghee', 'Ghee')], default=None, max_length=30)),
                ('material_used', models.CharField(choices=[('Normal', 'Normal'), ('Ragi', 'Ragi'), ('Jonna', 'Jonna')], default=None, max_length=30)),
                ('item_added_date', models.DateTimeField(auto_now_add=True)),
                ('item_price', models.PositiveIntegerField(blank=True, null=True)),
                ('item_available', models.BooleanField(default=True)),
                ('item_id', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
